before_script:
  - bundle install --jobs=3 --retry=3
  - cp config/database.example.yml config/database.yml
  - bundle exec rake db:drop db:create db:migrate db:test:prepare

stages:
  - test

rspec:
  stage: test
  script:
    - bundle exec rspec
  tags:
    - ruby
    - postgres
    - redis
