language: ruby
cache: bundler
rvm: 2.2
install: bundle install --jobs=3 --retry=3
services:
  - redis-server
before_script:
  - cp config/database.example.yml config/database.yml
  - bundle exec rake db:drop db:create db:migrate db:test:prepare
script: bundle exec rspec
